config/routes.rb
Rails.application.routes.draw do
  namespace :octobot do
    resources :languages do
      member do
        get 'trends'
      end
    end
    resource :status, only: :update, controller: :trend_statuses
    root 'trends#index'
  end

  namespace :foodbot do
    resources :retailers
    resources :products do
      member do
        get 'deals'
      end
    end
    root 'deals#index'
  end

  get 'crawler', to: 'crawler#index'

  root 'pages#home'
end

app/models/foodbot.rb
module Foodbot
  def self.table_name_prefix
    'foodbot_'
  end
end

app/models/foodbot/deal.rb
# == Schema Information
#
# Table name: foodbot_deals
#
#  id            :integer          not null, primary key
#  product_id    :integer
#  retailer_id   :integer
#  description   :string(255)
#  image         :string(255)
#  discount      :string(255)
#  price_new     :string(255)
#  price_old     :string(255)
#  quantity      :string(255)
#  date          :string(255)
#  download_date :date
#

module Foodbot
  class Deal < ApplicationRecord
    include HasDownloadUrl

    belongs_to :retailer, class_name: 'Foodbot::Retailer'
    belongs_to :product, class_name: 'Foodbot::Product'

    scope :latest, -> { where(download_date: maximum(:download_date)) }
    scope :current, -> { includes(:retailer).latest }

    class << self
      def process_deals(product, retailer)
        link = download_url(q: product.title, retailer: retailer.url)
        html = Nokogiri::HTML(BotBrowser.download(link, js: true))
        # html = Nokogiri::HTML(File.open(Rails.root.join('public', 'pages/foodbot.html')))
        crawler = Foodbot::DealCrawler.new(Foodbot::Deal, html, product, retailer)
        crawler.run
      end
    end
  end
end

app/models/foodbot/deal_crawler.rb
module Foodbot
  class DealCrawler < Crawler
    def initialize(model, content, product, retailer)
      @product = product
      @retailer = retailer
      super(model, content)
    end

    def run
      deals = []
      super do |entity|
        next unless Foodbot::Deal.where(description: entity[:description], download_date: entity[:download_date]).count.zero?
        deals << Foodbot::Deal.create(entity)
      end
      deals
    end

    private

    def product_id
      @product.id
    end

    def retailer_id
      @retailer.id
    end

    %i[description discount price_new price_old quantity date].each do |method|
      define_method(method) do
        extract_value(__method__.to_s)
      end
    end

    def image
      extract_value(__method__.to_s) do |value|
        value.attr('src').text
      end
    end
  end
end

app/models/foodbot/product.rb
# == Schema Information
#
# Table name: foodbot_products
#
#  id     :integer          not null, primary key
#  title  :string(255)
#  active :boolean
#

module Foodbot
  class Product < ApplicationRecord
    include HasStatus

    validates :title, presence: true, uniqueness: true

    class << self
      def process_products
        products = {}
        active.each do |product|
          products[product.title] = Foodbot::Retailer.process_retailers(product)
        end
        products
      end
    end
  end
end

app/models/foodbot/retailer.rb
# == Schema Information
#
# Table name: foodbot_retailers
#
#  id     :integer          not null, primary key
#  title  :string(255)
#  url    :string(255)
#  day    :string(255)
#  active :boolean
#

module Foodbot
  class Retailer < ApplicationRecord
    include HasStatus
    include HasDay

    validates :title, presence: true, uniqueness: true
    validates :day, presence: true, inclusion: { in: Date::DAYNAMES.map(&:downcase) }

    class << self
      def process_retailers(product)
        retailers = {}
        today.active.each do |retailer|
          retailers[retailer.title] = Foodbot::Deal.process_deals(product, retailer)
        end
        retailers
      end
    end
  end
end

app/controllers/foodbot/base_controller.rb
module Foodbot
  class BaseController < ApplicationController
    before_action :set_foodbot_navbar

    private

    def set_foodbot_navbar
      @navbar_items = [
        {
          title: 'Deals',
          path: foodbot_root_path
        },
        {
          title: 'Products',
          path: foodbot_products_path
        },
        {
          title: 'Retailers',
          path: foodbot_retailers_path
        }
      ]
    end
  end
end

app/controllers/foodbot/deals_controller.rb
module Foodbot
  class DealsController < BaseController
    include DealsList
    include HasProducts

    before_action :set_products
    before_action :set_all_deals

    def index
      @deals = @deals_all
    end
  end
end

app/controllers/foodbot/products_controller.rb
module Foodbot
  class ProductsController < BaseController
    include HasProducts
    include DealsList

    before_action :set_product, only: [:show, :edit, :update, :destroy]
    before_action :set_products, only: [:deals]
    before_action :set_all_deals, only: [:deals]

    def index
      @products = Product.order(:title)
    end

    def show; end

    def new
      @product = Product.new(active: true)
    end

    def edit; end

    def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to @product, notice: 'Product type was successfully created.'
      else
        render :new
      end
    end

    def update
      if @product.update(product_params)
        redirect_to @product, notice: 'Product type was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @product.destroy
      redirect_to foodbot_products_url, notice: 'Product type was successfully destroyed.'
    end

    def deals
      @deals = Deal.includes(:retailer).latest.where(product: params[:id])
      render template: 'foodbot/deals/index'
    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:foodbot_product).permit(:title, :active)
    end
  end
end

app/controllers/foodbot/retailers_controller.rb
module Foodbot
  class RetailersController < BaseController
    before_action :set_retailer, only: [:show, :edit, :update, :destroy]

    def index
      @retailers = Retailer.all
    end

    def show; end

    def new
      @retailer = Retailer.new(active: true)
    end

    def edit; end

    def create
      @retailer = Retailer.new(retailer_params)

      if @retailer.save
        redirect_to @retailer, notice: 'Retailer was successfully created.'
      else
        render :new
      end
    end

    def update
      if @retailer.update(retailer_params)
        redirect_to @retailer, notice: 'Retailer was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @retailer.destroy
      redirect_to foodbot_retailers_url, notice: 'Retailer was successfully destroyed.'
    end

    private

    def set_retailer
      @retailer = Retailer.find(params[:id])
    end

    def retailer_params
      params.require(:foodbot_retailer).permit(:title, :day, :url, :active)
    end
  end
end

app/views/foodbot/retailers/_form.html.erb
<%= form_with(model: retailer, local: true) do |form| %>
  <% if retailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(retailer.errors.count, "error") %> prohibited this retailer from being saved:</h2>

      <ul>
      <% retailer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :title, id: :retailer_title, class: 'input', placeholder: :title %>
  </div>

  <div class="field">
    <%= form.text_field :url, id: :retailer_url, class: 'input', placeholder: :url %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.select(:day, Date::DAYNAMES.map(&:downcase)) %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :retailer_active %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-primary' %>
  </div>
<% end %>

app/views/foodbot/retailers/edit.html.erb
<h1 class="title">Editing Retailer</h1>

<%= render 'form', retailer: @retailer %>

<hr/>

<%= link_to 'Show', @retailer, class: 'button is-link' %>
<%= link_to 'Back', foodbot_retailers_path, class: 'button is-text' %>

app/views/foodbot/retailers/index.html.erb
<h1 class="title">Retailers</h1>

<% unless @retailers.blank? %>
  <table class="table is-striped">
    <thead>
    <tr>
      <th>Title</th>
      <th>Day</th>
      <th>Url</th>
      <th>Active</th>
      <th class="has-text-centered" colspan="3">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @retailers.each do |retailer| %>
      <tr>
        <td><%= retailer.title %></td>
        <td><%= retailer.day %></td>
        <td><%= retailer.url %></td>
        <td><%= retailer.active %></td>
        <td><%= link_to 'Show', retailer %></td>
        <td><%= link_to 'Edit', edit_foodbot_retailer_path(retailer) %></td>
        <td><%= link_to 'Destroy', retailer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <hr/>
<% end %>

<%= link_to 'New Retailer', new_foodbot_retailer_path, class: 'button is-link' %>

app/views/foodbot/retailers/new.html.erb
<h1 class="title">New Retailer</h1>

<%= render 'form', retailer: @retailer %>

<hr/>

<%= link_to 'Back', foodbot_retailers_path, class: 'button is-text' %>

app/views/foodbot/retailers/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @retailer.title %>
</p>

<p>
  <strong>Day:</strong>
  <%= @retailer.day %>
</p>

<p>
  <strong>Url:</strong>
  <%= @retailer.url %>
</p>

<p>
  <strong>Active:</strong>
  <%= @retailer.active %>
</p>

<hr/>

<%= link_to 'Edit', edit_foodbot_retailer_path(@retailer), class: 'button is-link' %>
<%= link_to 'Back', foodbot_retailers_path, class: 'button is-text' %>