config/routes.rb
Rails.application.routes.draw do
  namespace :octobot do
    resources :languages do
      member do
        get 'trends'
      end
    end
    resource :status, only: :update, controller: :trend_statuses
    root 'trends#index'
  end

  namespace :foodbot do
    resources :retailers
    resources :products do
      member do
        get 'deals'
      end
    end
    root 'deals#index'
  end

  get 'crawler', to: 'crawler#index'

  root 'pages#home'
end

app/models/octobot.rb
module Octobot
  def self.table_name_prefix
    'octobot_'
  end
end

app/models/octobot/language.rb
# == Schema Information
#
# Table name: octobot_languages
#
#  id     :integer          not null, primary key
#  title  :string(255)
#  active :boolean
#

module Octobot
  class Language < ApplicationRecord
    include HasStatus

    class << self
      def process_languages
        trends = {}
        return trends unless should_run?
        languages = Language.active
        languages.each do |language|
          trends[language.title.downcase] = Octobot::Trend.process_trends(language)
        end
        trends
      end

      private

      def should_run?
        settings = YAML.load(File.read(settings_path))
        return false unless settings['day'] == Date.today.strftime('%A').downcase
        true
      end

      def settings_path
        Rails.root.join('config', 'swarm/octobot/settings.yml')
      end
    end
  end
end

app/models/octobot/trend.rb
# == Schema Information
#
# Table name: octobot_trends
#
#  id                :integer          not null, primary key
#  language_id       :integer
#  title             :string(255)
#  description       :text(65535)
#  language_selector :string(255)
#  link              :string(255)
#  stars             :integer
#  forks             :integer
#  stats             :string(255)
#  active            :boolean
#  download_date     :date
#

module Octobot
  class Trend < ApplicationRecord
    include HasDownloadUrl
    include HasStatus

    belongs_to :language, class_name: 'Octobot::Language'

    class << self
      def process_trends(language)
        link = download_url(language: language.title.downcase)
        html = Nokogiri::HTML(BotBrowser.download(link, js: false))
        # html = Nokogiri::HTML(File.open(Rails.root.join('public', 'pages/octobot.html')))
        crawler = Octobot::TrendCrawler.new(Octobot::Trend, html, language)
        crawler.run
      end
    end
  end
end

app/models/octobot/trend_crawler.rb
module Octobot
  class TrendCrawler < Crawler
    def initialize(model, content, language)
      @language = language
      super(model, content)
    end

    def run
      trend_items = []
      super do |entity|
        next if entity[:description].is_chinese?
        next unless Octobot::Trend.where(title: entity[:title]).count.zero?
        trend_items << Octobot::Trend.create(entity)
      end
      trend_items
    end

    private

    def language_id
      @language.id
    end

    %i[title description language_selector].each do |method|
      define_method(method) do
        extract_value(__method__.to_s)
      end
    end

    %i[stars forks].each do |method|
      define_method(method) do
        extract_value(__method__.to_s) do |value|
          value.text.strip.delete(',').to_i
        end
      end
    end

    def link
      extract_value(__method__.to_s) do |value|
        'https://github.com' + value.attr('href').text.strip
      end
    end

    def stats
      extract_value(__method__.to_s) do |value|
        value.last.text.strip
      end
    end

    def active
      true
    end
  end
end

app/models/octobot/trend_item.rb
module Octobot
  class TrendItem < Crawler
    def initialize(model, content, language)
      @language = language
      super(model, content)
    end

    def language_id
      @language.id
    end

    %i[title description language_selector].each do |method|
      define_method(method) do
        extract_value(__method__.to_s)
      end
    end

    %i[stars forks].each do |method|
      define_method(method) do
        extract_value(__method__.to_s) do |value|
          value.text.strip.delete(',').to_i
        end
      end
    end

    def link
      extract_value(__method__.to_s) do |value|
        'https://github.com' + value.attr('href').text.strip
      end
    end

    def stats
      extract_value(__method__.to_s) do |value|
        value.last.text.strip
      end
    end

    def checked
      false
    end

    def download_date
      Date.today
    end
  end
end

app/controllers/octobot/base_controller.rb
module Octobot
  class BaseController < ApplicationController
    before_action :set_octobot_navbar

    private

    def set_octobot_navbar
      @navbar_items = [
        {
          title: 'Trends',
          path: octobot_root_path,
        },
        {
          title: 'Languages',
          path: octobot_languages_path,
        }
      ]
    end
  end
end

app/controllers/octobot/languages_controller.rb
module Octobot
  class LanguagesController < BaseController
    include HasLanguages

    before_action :set_language, only: [:show, :edit, :update, :destroy]
    before_action :set_languages, only: [:trends]

    def index
      @languages = Language.all
    end

    def show; end

    def new
      @language = Language.new(active: true)
    end

    def edit; end

    def create
      @language = Language.new(language_params)

      if @language.save
        redirect_to @language, notice: 'Language was successfully created.'
      else
        render :new
      end
    end

    def update
      if @language.update(language_params)
        redirect_to @language, notice: 'Language was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @language.destroy
      redirect_to octobot_languages_url, notice: 'Language was successfully destroyed.'
    end

    def trends
      @trends = Trend.includes(:language).active.where(language: params[:id]).decorate
      render 'octobot/trends/index'
    end

    private

    def set_language
      @language = Octobot::Language.find(params[:id])
    end

    def language_params
      params.require(:octobot_language).permit(:title, :active)
    end
  end
end

app/controllers/octobot/trend_statuses_controller.rb
module Octobot
  class TrendStatusesController < TrendsBaseController
    def update
      @trends.update_all(active: false)
      flash[:success] = 'Marked as checked!'
      redirect_to octobot_root_path
    end
  end
end

app/controllers/octobot/trends_base_controller.rb
module Octobot
  class TrendsBaseController < BaseController
    before_action :set_trends

    private

    def set_trends
      @trends = Trend.includes(:language).active
    end
  end
end

app/controllers/octobot/trends_controller.rb
module Octobot
  class TrendsController < TrendsBaseController
    include HasLanguages

    before_action :set_languages

    def index
      @trends = @trends.decorate
    end
  end
end

app/views/octobot/languages/_form.html.erb
<%= form_with(model: language, local: true) do |form| %>
  <% if language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% language.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :title, id: :language_title, class: 'input', placeholder: :title %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :language_active %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-primary' %>
  </div>
<% end %>

app/views/octobot/languages/edit.html.erb
<h1 class="title">Editing Language</h1>

<%= render 'form', language: @language %>

<hr/>

<%= link_to 'Show', @language, class: 'button is-link' %>
<%= link_to 'Back', octobot_languages_path, class: 'button is-text' %>

app/views/octobot/languages/index.html.erb
<h1 class="title">Languages</h1>

<% unless @languages.blank? %>
  <table class="table is-striped">
    <thead>
    <tr>
      <th>Title</th>
      <th>Active</th>
      <th class="has-text-centered" colspan="3">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.title %></td>
        <td><%= language.active %></td>
        <td><%= link_to 'Show', language %></td>
        <td><%= link_to 'Edit', edit_octobot_language_path(language) %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <hr/>
<% end %>

<%= link_to 'New Language', new_octobot_language_path, class: 'button is-link' %>

app/views/octobot/languages/new.html.erb
<h1 class="title">New Language</h1>

<%= render 'form', language: @language %>

<hr/>

<%= link_to 'Back', octobot_languages_path, class: 'button is-text' %>

app/views/octobot/languages/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @language.title %>
</p>

<p>
  <strong>Active:</strong>
  <%= @language.active %>
</p>

<hr/>

<%= link_to 'Edit', edit_octobot_language_path(@language), class: 'button is-link' %>
<%= link_to 'Back', octobot_languages_path, class: 'button is-text' %>